name: calculetor
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:

  flutter:
    sdk: flutter
  icons_launcher: ^3.0.0
  flutter_lints: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  math_expressions: ^2.6.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  auto_size_text: ^3.0.0
  better_player: ^0.0.84
  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  flutter_markdown: ^0.7.3+2
  url_launcher: ^6.3.0
  http: ^1.2.2
  package_info_plus: ^8.0.2
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


icons_launcher:
  image_path: "assets/calculetor.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - CHANGELOG.md